[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "=0.8.6"
clap = "4.5.53"
itertools = "0.14.0"
nom = "8.0.0"
num-integer = "0.1.46"
rayon = "1.11.0"
regex = "1.12.2"
ring-algorithm = "0.8.0"
time = "0.3.44"

[profile.test]
opt-level = 3
